### ISSUE TITLE
monomorphic lambda calculus の訳語？

### ISSUE THREAD

**Issue by erutuf** [cpdt-japanese/cpdt-japanese#2]
Intro.v に出てくる monomorphic lambda calculus に一般的な訳はあるのか？

**Comment by nobsun** [comment]
polymorphic lambda calculus に「多相ラムダ計算」という訳語をあてるようなので、それと対比するなら、mononorphic lambda calculus は「単相ラムダ計算」となりそうですが。
simply typed lambda calculus と同じ意味で使っていて、対比を強調しないなら「単純型付きラムダ計算」もありかもしれませんね。

**Comment by erutuf** [comment]
Intro.v の fluiddynamics さんの担当の部分だと、依存型(のある Coq)と対比して Twelf のシステムについて monomorphic lambda calculus という言葉を使っているように見えます。
リテラルに「単相ラムダ計算」としてみましょうか> fluiddynamics さん

**Comment by fluiddynamics** [comment]
「単相ラムダ計算」としました
